### ISSUE TITLE
[StoreFront] Modernize Microservices to Quarkus

### ISSUE THREAD

**Issue by csantanapr** [cloud-native-toolkit/planning#705]
Implement the Storefront backend microservices in Quarkus.

- [x] Inventory - https://github.com/ibm-garage-ref-storefront/planning/issues/78
- [x] Catalog - https://github.com/ibm-garage-ref-storefront/planning/issues/79
- [x] Authentication with Keycloak - https://github.com/ibm-garage-ref-storefront/planning/issues/82
- [x] Orders - https://github.com/ibm-garage-ref-storefront/planning/issues/81
- [x] Customer - https://github.com/ibm-garage-ref-storefront/planning/issues/80
- [x] Once the implementation is done, integrate these microservices with the Storefront UI. - https://github.com/ibm-garage-ref-storefront/planning/issues/83
- [x] Update the [Storefront reference website](https://cloudnativereference.dev/) with `Deploy Storefront (Quarkus Version) locally on your machine` under `Deployments`. - https://github.com/ibm-garage-ref-storefront/planning/issues/84

**Comment by phemankita** [comment]
Enabled Quarkus for all storefront java backend services

- [Inventory microservice](https://github.com/ibm-garage-ref-storefront/inventory-ms-quarkus)
- [Catalog microservice](https://github.com/ibm-garage-ref-storefront/catalog-ms-quarkus)
- [Orders microservice](https://github.com/ibm-garage-ref-storefront/orders-ms-quarkus)
- [Customer microservice](https://github.com/ibm-garage-ref-storefront/customer-ms-quarkus)

Authentication is done using Keycloak - [Instructions for storefront](https://cloudnativereference.dev/related-repositories/keycloak)

Deploying the storefront locally - https://cloudnativereference.dev/deployments/quarkus

**Comment by csantanapr** [comment]
Good progress @phemankita 👍

**Comment by phemankita** [comment]
This is complete
